# Generated by Django 4.2.3 on 2024-03-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_certificate_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="profiles",
            field=models.ManyToManyField(
                related_name="certificates", to="projects.profile"
            ),
        ),
    ]
